### ISSUE TITLE
[Afaceri] Node scraper fails if downloads directory is not created

### ISSUE THREAD

**Issue by margelatu** [code4romania/czl-scrape#62]
Running the node scraper will fail if the `downloads` folder is not created beforehand.

```
$ node server/server.js
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer
Downloading file from http://www.antreprenoriat.gov.ro/wp-content/uploads/2017/01/nota-fundam-oug-internationalizare-semnaturi-mfp-mj-20-01-2017-1.pdf...
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

Error: ENOENT: no such file or directory, open './downloads/nota-fundam-oug-internationalizare-semnaturi-mfp-mj-20-01-2017-1.pdf'
```

Workaround is to pre-create the `downloads` directory.

**Comment by ciprian-chichirita** [comment]
cred ca il pot face eu? (in principiu o sa verific din node daca exista folderul downloads, daca nu, il creez)

**Comment by margelatu** [comment]
@ciprian-chichirita : ti l-am alocat.

**Comment by margelatu** [comment]
Ne mutam in JIRA, noul link pentru issue este [https://codeforromania.atlassian.net/browse/CZL-1](https://codeforromania.atlassian.net/browse/CZL-1)
