### ISSUE TITLE
[Mediu] Wrong spider name in run instructions

### ISSUE THREAD

**Issue by margelatu** [code4romania/czl-scrape#64]
The instructions say one should run: `scrapy crawl mdrap -a token=xxxx` to execute the spider. The spider name is incorrect though. It should be `mmediu` instead of `mdrap`.

The line should therefore be `scrapy crawl mmediu -a token=xxxx`.

**Comment by costibleotu** [comment]
Fixed it in pull request #78

**Comment by margelatu** [comment]
Confirmed, fixed with #78.
