### ISSUE TITLE
[Sanatate] No logging whatsoever

### ISSUE THREAD

**Issue by margelatu** [code4romania/czl-scrape#65]
The scraper works fine, but there is no logging. Logs would be very helpful, especially long-term.

**Comment by Owlree** [comment]
Can we standardize necessary logging info across all scrapers before adding this?

**Comment by margelatu** [comment]
Good idea. Created #66

**Comment by margelatu** [comment]
@Owlree : see https://github.com/code4romania/czl-scrape/wiki/Ghid-Pentru-Logging for a rough guideline for logging.

**Comment by Owlree** [comment]
On it.

**Comment by margelatu** [comment]
Ne mutam in JIRA, noul link este https://codeforromania.atlassian.net/browse/CZL-4
