### ISSUE TITLE
[Dialog] Missing feedback deadline date or days remaining

### ISSUE THREAD

**Issue by margelatu** [code4romania/czl-scrape#87]
The scraper does not retrieve the feedback deadline date and does not send it to the API as remaining days of feedback.

**Comment by xlotlu** [comment]
If date / days are unknown, the feedback deadline [can now be auto-computed](https://github.com/code4romania/czl-api/commit/3d8c6d807a98afb8ba94193c3fb0807cbf6509cc).
If too lazy to extract days from date, [#8 will soon happen](https://github.com/code4romania/czl-api/issues/8).

**Comment by margelatu** [comment]
@xlotlu : agreed, but in this case the feedback deadline is found in the pages so it can be scraped.

**Comment by margelatu** [comment]
Ne mutam in JIRA, noul link este https://codeforromania.atlassian.net/browse/CZL-2
